export const lessons = [
  {
    name: "Монгол хэл, Уран зохиол",
    price: 1.2,
    img: "literature",
    img_detail: "literature-detail",
    checked: false,
  },
  {
    name: "Математик",
    price: 2.0,
    img: "math",
    img_detail: "math-detail",
    checked: false,
  },
  {
    name: "Мэдээлэл технологи",
    price: 2.5,
    img: "it",
    img_detail: "it-detail",
    checked: false,
  },
  {
    name: "Физик",
    price: 3.0,
    img: "physics",
    img_detail: "physics-detail",
    checked: false,
  },
  {
    name: "Түүх",
    price: 3.5,
    img: "history",
    img_detail: "history-detail",
    checked: false,
  },
  {
    name: "Англи хэл",
    price: 3.0,
    img: "english",
    img_detail: "english-detail",
    checked: false,
  },
  {
    name: "Хөгжим бүжиг",
    price: 2.0,
    img: "culture",
    img_detail: "culture-detail",
    checked: false,
  },
  {
    name: "Биологи",
    price: 2.0,
    img: "biology",
    img_detail: "biology-detail",
    checked: false,
  },
  {
    name: "Нийгэм",
    price: 2.0,
    img: "economy",
    img_detail: "economy-detail",
    checked: false,
  },
  {
    name: "Хими",
    price: 2.0,
    img: "chemic",
    img_detail: "chemic-detail",
    checked: false,
  },
  {
    name: "Газар зүй",
    price: 2.0,
    img: "geography",
    img_detail: "geography-detail",
    checked: false,
  },
  {
    name: "Биеийн тамир,спорт",
    price: 2.0,
    img: "sport",
    img_detail: "sport-detail",
    checked: false,
  },
];
